[phases.setup]
nixPkgs = ["nodejs_22", "nodePackages.pnpm"]

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = [
  "BASE_PATH=/ NODE_ENV=production pnpm --filter @workspace/studywave run build",
  "pnpm --filter @workspace/api-server run build"
]

[start]
cmd = "pnpm --filter @workspace/db run push-force && NODE_ENV=production node --enable-source-maps artifacts/api-server/dist/index.mjs"
